# GitHub Actions Workflow Datei

name: Run Cucumber Tests and Publish HTML Report

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Run Cucumber Tests
        run: mvn clean test -Dbrowser=chromeheadless

      - name: Upload HTML Report (direct .html file)
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-reports.html

      - name: Upload Cucumber Report ZIP
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: cucumber-report.zip
